// Date: 01/11/2016 11:06:40
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package com.MrpYA45.TheBoyScoutMod.entity.model;

import net.minecraft.client.renderer.entity.model.EntityModel;
import net.minecraft.client.renderer.entity.model.RendererModel;
import net.minecraft.entity.Entity;

public class ModelFish <T extends Entity> extends EntityModel<T>
{
  //fields
    RendererModel Cuerpo;
    RendererModel Cola1;
    RendererModel Cola2;
    RendererModel AletaArriba;
    RendererModel Aleta1;
    RendererModel Aleta2;
  
  public ModelFish()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      Cuerpo = new RendererModel(this, 56, 0);
      Cuerpo.addBox(0F, 0F, 0F, 1, 2, 3);
      Cuerpo.setRotationPoint(0F, 20F, 0F);
      Cuerpo.setTextureSize(64, 32);
      Cuerpo.mirror = true;
      setRotation(Cuerpo, 0F, 0F, 0F);
      Cola1 = new RendererModel(this, 53, 0);
      Cola1.addBox(0F, 0F, 0F, 0, 2, 1);
      Cola1.setRotationPoint(0.5F, 21F, 2F);
      Cola1.setTextureSize(64, 32);
      Cola1.mirror = true;
      setRotation(Cola1, 0.7853982F, 0F, 0F);
      Cola2 = new RendererModel(this, 48, 0);
      Cola2.addBox(0F, 0F, 0F, 0, 1, 2);
      Cola2.setRotationPoint(0.5F, 21F, 2F);
      Cola2.setTextureSize(64, 32);
      Cola2.mirror = true;
      setRotation(Cola2, 0.7853982F, 0F, 0F);
      AletaArriba = new RendererModel(this, 43, 0);
      AletaArriba.addBox(0F, 0F, 0F, 0, 1, 2);
      AletaArriba.setRotationPoint(0.5F, 19.5F, 0.5F);
      AletaArriba.setTextureSize(64, 32);
      AletaArriba.mirror = true;
      setRotation(AletaArriba, 0F, 0F, 0F);
      Aleta1 = new RendererModel(this, 40, 0);
      Aleta1.addBox(0F, 0F, 0F, 0, 1, 1);
      Aleta1.setRotationPoint(0F, 20.5F, 1.5F);
      Aleta1.setTextureSize(64, 32);
      Aleta1.mirror = true;
      setRotation(Aleta1, 0F, -0.1745329F, 0F);
      Aleta2 = new RendererModel(this, 37, 0);
      Aleta2.addBox(0F, 0F, 0F, 0, 1, 1);
      Aleta2.setRotationPoint(1F, 20.5F, 1.5F);
      Aleta2.setTextureSize(64, 32);
      Aleta2.mirror = true;
      setRotation(Aleta2, 0F, 0.1745329F, 0F);
  }
  
  public void render(T entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    Cuerpo.render(f5);
    Cola1.render(f5);
    Cola2.render(f5);
    AletaArriba.render(f5);
    Aleta1.render(f5);
    Aleta2.render(f5);
  }
  
  private void setRotation(RendererModel model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, T e)
  {
    super.setRotationAngles(e, f, f1, f2, f3, f4, f5);
  }

}
